categories:
- SAM
description: Fgbio SAM/BAM manipulation tools.
homepage_url: https://github.com/fulcrumgenomics/fgbio
long_description: |
    A set of tools to analyze genomic data with a focus on Next Generation Sequencing.
name: fgbio
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/fgbio
type: unrestricted
